### ISSUE TITLE
想请作者加入一个绕开大陆地址和大陆ip的功能，也就是和以前的绕开局域网和大陆的功能似的，谢谢！

### ISSUE THREAD

**Issue by aaaayong** [CGDF-Github/SSD-Windows#10]
国外全走代理这个功能挺好的，一直开着代理的话现在只能用PAC模式，但是上有些国外网站着实慢的可怜。希望作者能再次重新加入该功能

**Comment by CGDF-Github** [comment]
https://github.com/CGDF-Github/SSD-Windows/issues/2
