### ISSUE TITLE
指定的可执行文件不是此操作系统平台的有效应用程序

### ISSUE THREAD

**Issue by CasparLi** [CGDF-Github/SSD-Windows#12]
32bit win10. SSD版本: 0.1.7.0

程序启动后没有异常, 但不能正确链接到服务器, 点击任何功能(更新, 设置等)会报错:
![image](https://user-images.githubusercontent.com/3424447/50389288-87063b00-0763-11e9-8678-2bea609b9cef.png)

日志中出现如下信息: 
[2018-12-24 10:03:23] [E] Failed to start SIP003 plugin: 指定的可执行文件不是此操作系统平台的有效应用程序。

这是因为系统是32位所以不兼容么?

**Comment by CGDF-Github** [comment]
插件问题，问机场主去

**Comment by TheCGDF** [comment]
已修复：https://github.com/TheCGDF/SSD-Windows/commit/46a4f0c34b7422ff230565a8dde61bb58dfdd6f5

相关issue：https://github.com/TheCGDF/SSD-Windows/issues/38

致歉：因当时的无知与耐心缺失导致误判，以至于两年之后才得以正确审视并修复此问题，对此感到十分抱歉
