### ISSUE TITLE
HTTP Auto Proxy Detection Worker Process 的进程堆积

### ISSUE THREAD

**Issue by GwokTsyn** [CGDF-Github/SSD-Windows#17]
任务管理器中观察到大量名为 HTTP Auto Proxy Detection Worker Process 的进程，程序名为 pacjsworker.exe，位于C:\Windows\System32，进程数量随着使用逐渐增加，手动结束进程无效（进程仍在，换了个PID），重启会清零。

搜索过SSR项目有过一样的问题
https://github.com/shadowsocksrr/shadowsocksr-csharp/issues/149

不懂编程，只是想提交问题，忘见谅。

**Comment by CGDF-Github** [comment]
此问题已在上游SS的历史issue中：
https://github.com/shadowsocks/shadowsocks-windows/issues/1979
请尝试升级到最新版Windows，此问题**可能**会解决。
关于此问题的后续，也许微软会修复，也许上游SS会修复。本项目将跟随上游SS处理。

**Comment by database64128** [comment]
在19H1预览版18351和20H1预览版18850中，pacjsworker.exe的行为是一致的，旧的进程会在5分钟后自动退出。因此，将来这个issue只会影响1809这个系统版本。上游开发者没有对ss进行修改的意向。
