### ISSUE TITLE
SSD需要部署一个服务器端的程序，目前推荐哪些能被拿来使用的windows vps/微软windows平台操作系统云服务器资源？

### ISSUE THREAD

**Issue by OsQOscar** [CGDF-Github/SSD-Windows#18]
需要将服务器端软件部署到windows vps，注意：云服务器操作系统是微软microsoft windows的平台，需要windows服务器端源文件
（SSD服务器端部署在windows vps上，不是linux vps上）

**Comment by CGDF-Github** [comment]
SSD直接使用原版SS的服务端

**Comment by OsQOscar** [comment]
当前正在使用SSR在windows vps上的部署脚本并且运行正常，我需要在同一windows vps上同时运行SS SSR SSD v2ray vpn ftp http文件服务多种类型的分享程序

**Comment by OsQOscar** [comment]
![image](https://user-images.githubusercontent.com/34408331/53854992-b7414400-4006-11e9-8853-f12085c39a48.png)

**Comment by OsQOscar** [comment]
原作者删除了youtube视频，但是目前windows vps上仍然可以直接用一键zip包成功搭建SSR服务器端

**Comment by CGDF-Github** [comment]
安装SS服务端即可，狭义的SSD只是一个客户端

**Comment by CGDF-Github** [comment]
ss://开头的链接依然可用

**Comment by OsQOscar** [comment]
目前手头上至少有400台windows操作系统云服务器，只有客户端太浪费资源了

**Comment by CGDF-Github** [comment]
我听不懂什么叫“只有客户端太浪费资源了”
