### ISSUE TITLE
关于自动测试延迟的问题

### ISSUE THREAD

**Issue by LYCX2015** [CGDF-Github/SSD-Windows#4]
请问测试延迟功能在哪里体现，试用了一下，没有找到该功能哦~

**Comment by CGDF-Github** [comment]
@LYCX2015 右键菜单->选择服务器

**Comment by LYCX2015** [comment]
@CGDF-Github 服务器那里有个pending，没有看到有延迟。

**Comment by CGDF-Github** [comment]
重启，等3秒，再看。
导入服务器之后不会立刻显示延迟的问题下个版本修复。
