### ISSUE TITLE
阅读了README的一点疑问，

### ISSUE THREAD

**Issue by ncs19960831** [CGDF-Github/SSD-Windows#6]
阅读了一遍README，感觉有些问题没有说清楚。

1. SSD是否是兼容SS或者说在SS基础上增加一些特定功能的软件？换而言之是否完全兼容SS？
2. 如果1中的问题的答案为肯定，可否在README或者Release里面注明当前同步的SS版本？
3.看到了v2ray，那么是否以后有兼容V2ray的可能性？或者参照1的问题可以使用v2ray搭建SS进行兼容？
望请回复

**Comment by ncs19960831** [comment]
看了一下release，Basic也许是SS的版本？但是Limit恕我愚钝，实在无法理解。
还有一点，如果SSR在没有混淆的情况下是否可以兼容？

**Comment by laincat** [comment]
下载打开该改版，可以看到“目前”“就是”“只多了”“扩展功能部分” 和“一些修改”。（就是只有引号部分内容）
（我真的不知道该从哪里吐槽你问的这些问题。。。

**Comment by Xeonacid** [comment]
Limit是当前最低可用版本，低于该版本的SSD会被强行升级

**Comment by CGDF-Github** [comment]
你有空balabala问这些为什么不自己下载下来看一下？明明下载下来之后一眼就能知道的答案非要在这里balabala地问，怎么，怕有病毒？
