### ISSUE TITLE
启动时程序抛出 ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by LinHongQing** [CGDF-Github/SSD-Windows#7]
初次使用正常，关闭再重新启动程序即抛出该错误，错误 log 如下：
[2018-09-11 08:55:43] [E] System.ArgumentOutOfRangeException: 索引超出范围。必须为非负值并小于集合大小。
参数名: index
   在 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   在 Shadowsocks.Controller.Strategy.StatisticsStrategy..ctor(ShadowsocksController controller)
   在 Shadowsocks.Controller.Strategy.StrategyManager..ctor(ShadowsocksController controller)
   在 Shadowsocks.Controller.ShadowsocksController..ctor()
   在 Shadowsocks.Program.Main()

**Comment by CGDF-Github** [comment]
这是内测已知的BUG，原因是删除了默认自带的www.baidu.com:-1导致的index异常。
同时删除默认自带的www.baidu.com:-1还会导致统计界面无法正常打开。
临时的解决办法为：删除 gui-config.json，重新导入订阅，之后请保留默认自带的www.baidu.com:-1节点。
本BUG会在android版发布第一个正式版之后进行修复。

**Comment by mouyase** [comment]
感谢
